### ISSUE TITLE
eWaterCycle BMI expects different get_time_units() vs. BMI 2.0

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/ewatercycle#379]
According to the BMI 2.0 specification, the function/method `get_time_units` should return the units of time like "s", "min", "h" or "d".

eWaterCycle expects the time units output to be parse-able to a datetime, like  `"seconds since 1970-01-01 00:00:00.0 +0000"`

**Comment by Peter9192** [comment]
Just for completeness, `seconds since 1970-01-01 00:00:00.0 +0000` is a perfectly valid time unit. However, not all valid time units are parsable to datetimes. So, at the very least, we should communicate clearly that we expect a more specific time unit than what's required by BMI for all our additional time utility methods.
