### ISSUE TITLE
Clarify to users that an eWaterCycle model is not the same as BMI

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/ewatercycle#401]
Users don't talk directly to the BMI, but via the ewatercycle wrapper.
Some methods look the same, and it can give the user the impression they're using the BMI directly.

Some of the most commonly used methods have the same name:

- initialize
- update
- get_value
- set_value
- finalize

Others are very similar:

- get_value_at_coords (instead of get_value_at_indices)
- set_value_at_coords (instead of set_value_at_indices)
- start_time (instead of get_start_time)
- etc...

It should be very clear to users that `model.method` uses eWaterCycle-specific syntax, while `model.bmi.method` gives them access to underlying BMI methods (such as `get_var_units`)

@RolfHut

**Comment by BSchilperoort** [comment]
[PyMT](https://pymt.readthedocs.io/en/latest/quickstart.html#run-a-model) has `model.var_units(var_name)`. This is missing from eWaterCycle

**Comment by RolfHut** [comment]
this is confusing indeed: I was under the impression that we inherit the bmi from the model and overload some of the methods in bmi with specific eWaterCycle versions to make it work.

**Comment by Peter9192** [comment]
The eWaterCycle model interface is modelled after PyMT. E.g. `setup` is a PyMT method, not a BMI method. Similarly, PyMT exposes `get_value`, not `get_value_at_indices`.

On top of that, we have added `get_value_at_coords`, `time_as_isostr`, etc because we needed them often, so for convenience. They are not meant to replace standard PyMT methods such as `get_value`, but rather to be additional to them.

**Comment by Peter9192** [comment]
See PyMT interface here: https://pymt.readthedocs.io/en/latest/usage.html#time

**Comment by BSchilperoort** [comment]
> The eWaterCycle model interface is modelled after PyMT

Yes, but I don't think this is clear enough in the current user documentation. I'll update the documentation to reflect this better.
