### ISSUE TITLE
Add Geopandas by default

### ISSUE THREAD

**Issue by Daafip** [eWaterCycle/ewatercycle#408]
Geopandas makes working with shapefiles and geographic data so much easier without having to dive deep into Fiona and shapely.
Would be nice in my opinion if eWaterCycle includes it by default. What are your takes on that?
https://geopandas.org/en/stable/index.html

**Comment by BSchilperoort** [comment]
The upsides:
- ease of use
- commonly used package.

Downsides: 
- more dependencies
  - geopandas shares dependencies with ESMValTool, if they require different versions it become difficult for us
- geopandas is pre-1.0 (so behavior can change quickly: more difficult to support).
  - Although their packaging info states `5 - Production/Stable` as the development status

I guess you would like to use geopandas due to the caravan shapefile containing multiple polygons? So far we have only had shapefiles with a single polygon which has been much simpler.

**Comment by sverhoeven** [comment]
Hype model also uses multiple polygons for forcing generation see https://github.com/eWaterCycle/ewatercycle-hype/tree/main/docs/data/Rhine_HYPE and https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/hydrology/recipe_hype.yml#L28

**Comment by Daafip** [comment]
> I guess you would like to use geopandas due to the caravan shapefile containing multiple polygons

Yes, that was my main intended use case. Selecting one polygon from many is one line using goepandas and 10 if i use fiona directly.

I personally also find it easy to use & quick for making maps. Given the shapefile is already required/retrieved for most forcing that makes it even quicker. Most users will probably use ArcGIS/QGIS though, so maybe it should be more a user addition if they want to use it. 


> * geopandas shares dependencies with ESMValTool,

Hadn't considered that, might make it tricky

**Comment by BSchilperoort** [comment]
I think due to the overlap in dependencies between ESMValTool and geopandas, it's better to not add geopandas as a dependency at this point in time. Of course we can reassess this at a later point in time.
