### ISSUE TITLE
update_until() alongside update() 

### ISSUE THREAD

**Issue by pauwiersma** [eWaterCycle/ewatercycle#460]
To run WflowJl I've added a `update_until()` function in the eWaterCycleModel class alongside the [`update()`](https://github.com/eWaterCycle/ewatercycle/blob/ee28ec645d160b3aed5791e95d9328ab1508fe4d/src/ewatercycle/base/model.py#L180)function. Is there a reason why `update_until() `is left out as a BMI function? If not it would be great to have it included in a next release so I don't need to make offline adjustments.

The function I added is 

```
    def update_until(self, time:float) -> None:
        """Advance model state until time"""
        self._bmi.update_until(time)
```
Thanks!

**Comment by BSchilperoort** [comment]
Hi Pau,

I think not all functions have been reimplemented in the eWaterCycleModel class because the bmi is still available, and we would want to hide some functionality from end users (e.g. `get_grid_size`). However this is mainly not clearly explained in the documentation, and I do think that `update_until` should be re-exposed. It was probably just forgotten (and usually we have been extracting the streamflow each timestep anyway. 

Related is this: https://github.com/eWaterCycle/grpc4bmi/issues/152)

By the way, in general you can (also) access the bmi through `model.bmi.`

**Comment by pauwiersma** [comment]
Hi Bart, thanks for the clarification. I didn't realize I could also do `model.bmi.update_until()`, that works and solves my problem so I'll close this issue if you agree.
