### ISSUE TITLE
Bug: wflow model class: NoSectionError: No section: 'API'

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/ewatercycle#76]
If `config.ini` does not have section "API", the section should be added to the config, for example:

```python
cfg["API"] = { "RiverRunoff": "2, m^3/s"}
```

In wflow.py, the implementation at [this line](https://github.com/eWaterCycle/ewatercycle/blob/c5cb64dfe252c63fa2c8e3ad86cc963cfe4f4abe/ewatercycle/models/wflow.py#L65)  `cfg.set(section, option, value)` works only if the section already exists.

**Comment by Peter9192** [comment]
You're right that this doesn't work, but I wouldn't call it a bug. At this point we assume that the config file passed to `setup` is nearly complete. If you want to add more section, this can be done in the config file before passing it to `setup`.

Consider it a bonus that it's already possible to overwrite some of the settings on `setup`, with the limitation that the section should already exist. We should come up with a better design with default section and parameters in the near future, rather than fix this, as it's probably a temporary feature anyway
